Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2019-04, with the labels that each got.

#354 Remove execute bit on systemd unit file
  manifests/instance_service.pp
Labels: bugfix

#362 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#364 (MODULES-8930) Fix stahnma/epel dependency failures
  spec/spec_helper_acceptance.rb
Labels: bugfix

#363 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance
