Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2019-01, with the labels that each got.

#343 pdksync - pdksync_heads/master-0-g9c815ea
  .travis.yml
  metadata.json
Labels: maintenance

#344 pdksync - pdksync_heads/master-0-g6814a87
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance

#345 (FM-7675) - Support has been removed for RHEL 6
  metadata.json
Labels: backwards-incompatible

#346 (MODULES-8539) Added 'accepted_payload_size' to resolver
  README.md
  manifests/resolver.pp
  spec/defines/resolver_spec.rb
  templates/haproxy_resolver_block.erb
Labels: feature

#349 pdksync - pdksync_1.9.0-0-g7281db5
  .puppet-lint.rc
  metadata.json
  spec/spec_helper.rb
Labels: maintenance
