Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2019-11, with the labels that each got.

#394 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#396 pdksync - FM-8499 - remove ubuntu14 support
  provision.yaml
Labels: backwards-incompatible

#397 (FM-8674) - Support added for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#398 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance
