Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2020-09, with the labels that each got.

#443 (IAC-988) - Removal of inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  .nodeset.yml
  CONTRIBUTING.md
  README.md
  REFERENCE.md
  manifests/backend.pp
  manifests/balancermember.pp
  manifests/frontend.pp
  manifests/init.pp
  manifests/instance.pp
  manifests/listen.pp
  manifests/resolver.pp
  metadata.json
Labels: bugfix

#445 Release version mergeback 4.3.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#442 Fix incorrect options order in HAproxy 2.2.x
  manifests/backend.pp
  spec/acceptance/basic_spec.rb
  templates/fragments/_options.erb
Labels: feature
