Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2022-10, with the labels that each got.

#528 (MAINT) Add support for Ubuntu 22.04
  metadata.json
Labels: feature

#530 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#533 pdksync - (CONT-189) Remove support for RedHat6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#534 (CONT-173) - Updating deprecated facter instances
  lib/facter/haproxy_version.rb
  spec/unit/facter/haproxy_version_spec.rb
Labels: bugfix

#526 update resolver parameters
  manifests/resolver.pp
  spec/defines/resolver_spec.rb
  templates/haproxy_resolver_block.erb
Labels: community
