Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2023-04, with the labels that each got.

#544 (Cont 779) Add Support for Puppet 8 / Drop Support for Puppet 6
  .devcontainer/devcontainer.json
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  manifests/balancermember.pp
  manifests/mailer.pp
  manifests/peer.pp
  metadata.json
  spec/acceptance/basic_spec.rb
  spec/acceptance/frontbackend_spec.rb
  spec/acceptance/listen_spec.rb
  spec/acceptance/mapfile_spec.rb
  spec/acceptance/userlist_spec.rb
  spec/classes/haproxy_spec.rb
  spec/defines/backend_spec.rb
  spec/defines/balancermember_spec.rb
  spec/defines/defaults_spec.rb
  spec/defines/frontend_spec.rb
  spec/defines/instance_service_spec.rb
  spec/defines/instance_spec.rb
  spec/defines/listen_spec.rb
  spec/defines/mailer_spec.rb
  spec/defines/mailers_spec.rb
  spec/defines/mapfile_entry_spec.rb
  spec/defines/mapfile_spec.rb
  spec/defines/peer_spec.rb
  spec/defines/peers_spec.rb
  spec/defines/resolver_spec.rb
  spec/defines/userlist_spec.rb
  spec/spec_helper.rb
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible

#548 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#549 (CONT-880) Update concat dependency
  metadata.json
Labels: dependencies

#550 pdksync - (MAINT) - Remove deprecated has_key
  manifests/backend.pp
  manifests/frontend.pp
Labels: maintenance
