Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2023-09, with the labels that each got.

#578 pdksync - (CAT-1366) - Fix issue url from old jira to github
  metadata.json
Labels: maintenance

#576 haproxy::backend: Always set $_sort_options_alphabetic
  manifests/backend.pp
Labels: bugfix, community

#579 Replace merge() with native puppet code
  manifests/config.pp
Labels: community

#584 (CAT-1426)-Removal of redhat/scientific/oraclelinux 6 for haproxy module
  manifests/instance_service.pp
  spec/acceptance/userlist_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#585 Update issue link in ReadMe
  README.md
Labels: maintenance
