Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2023-07, with the labels that each got.

#560 (maint) fix concat version in metadata.json
  metadata.json
Labels: maintenance

#559 (CONT-1181) - Fixing build failure for RedHat
  .rubocop_todo.yml
  spec/acceptance/listen_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#564 (CONT-1144) - Conversion of ERB to EPP templates
  REFERENCE.md
  lib/puppet/functions/haproxy/generate_error_message.rb
  lib/puppet/functions/haproxy/sort_bind.rb
  lib/puppet/functions/haproxy/validate_ip_addr.rb
  manifests/backend.pp
  manifests/balancermember.pp
  manifests/config.pp
  manifests/defaults.pp
  manifests/frontend.pp
  manifests/instance_service.pp
  manifests/listen.pp
  manifests/mailer.pp
  manifests/mailers.pp
  manifests/mapfile.pp
  manifests/mapfile/entry.pp
  manifests/peer.pp
  manifests/peers.pp
  manifests/resolver.pp
  spec/functions/generate_error_message_spec.rb
  spec/functions/sort_bind_spec.rb
  spec/functions/validate_ip_addr_spec.rb
  templates/empty.erb
  templates/fragments/_bind.epp
  templates/fragments/_bind.erb
  templates/fragments/_description.epp
  templates/fragments/_description.erb
  templates/fragments/_mode.epp
  templates/fragments/_mode.erb
  templates/fragments/_options.epp
  templates/fragments/_options.erb
  templates/haproxy-base.cfg.epp
  templates/haproxy-base.cfg.erb
  templates/haproxy_backend_block.epp
  templates/haproxy_backend_block.erb
  templates/haproxy_balancermember.epp
  templates/haproxy_balancermember.erb
  templates/haproxy_defaults_block.epp
  templates/haproxy_defaults_block.erb
  templates/haproxy_frontend_block.epp
  templates/haproxy_frontend_block.erb
  templates/haproxy_listen_block.epp
  templates/haproxy_listen_block.erb
  templates/haproxy_mailer.epp
  templates/haproxy_mailer.erb
  templates/haproxy_mailers_block.epp
  templates/haproxy_mailers_block.erb
  templates/haproxy_mapfile.epp
  templates/haproxy_mapfile.erb
  templates/haproxy_options_sorting.epp
  templates/haproxy_peer.epp
  templates/haproxy_peer.erb
  templates/haproxy_peers_block.epp
  templates/haproxy_peers_block.erb
  templates/haproxy_resolver_block.epp
  templates/haproxy_resolver_block.erb
  templates/instance_service_unit.epp
  templates/instance_service_unit.erb
Labels: feature

#557 Correct warnings about deprecated parameter
  manifests/frontend.pp
  manifests/listen.pp
Labels: bugfix, community
