Repository puppetlabs/puppetlabs-haproxy, pull requests merged in 2023-11, with the labels that each got.

#591 pdksync - [CAT-1541]: Adding github directory to pdkignore
  .pdkignore
Labels: maintenance

#592 merge_options: Switch default false->true
  manifests/config.pp
  manifests/params.pp
Labels: backwards-incompatible, community

#588 Add `merge_options` for `haproxy::defaults`
  REFERENCE.md
  manifests/defaults.pp
  spec/defines/defaults_spec.rb
Labels: feature, community

#594 Add bastelfreak to codeowners
  CODEOWNERS
Labels: community

#593 pdksync - 'CAT-945 - Update README.md LICENSE'
  README.md
Labels: maintenance
